echo "Erişim hakları ve dosyalar"
echo ""
echo "chmod octal file – dosya haklarını kullanıcı, grup ve herkes için ayrı ayrı sekizli olarak ekleyerek değiştirin:"
echo "4 – okuma (r)"
echo "2 – kayıt (w)"
echo "1 – verim (x)"
