echo "Arşivler:"
echo "" 
echo "tar cf file.tar files – dosyaları içeren file.tar adında bir tar arşivi oluşturun"
echo "tar xf file.tar – file.tar paketini açın"
echo "tar czf file.tar.gz files – Gzip sıkıştırmasıyla tar arşivi oluşturma"
echo "tar xzf file.tar.gz – katranı Gzip ile açın"
echo "tar cjf file.tar.bz2 – Bzip2 sıkıştırmasıyla bir tar arşivi oluşturun"
echo "tar xjf file.tar.bz2 – katranı Bzip2 ile açın"
echo "gzip file – dosyayı sıkıştırın ve file.gz olarak yeniden adlandırın"
echo "gzip -d file.gz – file.gz dosyasını dosyaya çıkartın"
