echo "Philes, Tsommandlar'ın temelidir:"
echo ""
echo "ls – dosya ve dizinlerin listesi"
echo "ls -al – gizli dizinler ve dosyalar içeren biçimlendirilmiş liste"
echo "cd dir – dizini şu şekilde değiştir: dir"
echo "cd – ana dizine geç"
echo "pwd – geçerli dizini göster"
echo "mkdir dir – geçerli dizini ekle: dir"
echo "rm -rf file – dosya veya klasörü sil"
echo "rm -r dir – dizini sildir"
echo "rm -r -f /path – dizini sildir"
echo "rm -f file – dosyayı zorla sil"
echo "rm -rf dir – dizini zorla sil dir"
echo "cp file1 file2 – dosya1'i dosya2'ye kopyala"
echo "cp -r dir1 dir2 – kopyala dir1 içinde dir2; yoksa dir2 dizini oluşturulacak"
echo "mv file1 file2 – dosya1'i dosya2'ye yeniden adlandırın veya taşıyın. dosya2 mevcut bir dizinse - dosya1'i dosya2 dizinine taşıyın"
echo "ln -s file link – dosya dosyasına sembolik bir bağlantı oluşturun"
echo "touch file – dosya oluştur"
echo "cat > file – dosyaya standart girdi gönder"
echo "more file – dosyanın içeriğini göster"
echo "head file – dosyanın ilk 10 satırını görüntüle"
echo "tail file – dosyanın son 10 satırını görüntüle"
echo "tail -f file – son 10 satırdan başlayarak dosyanın içeriğini büyüdükçe görüntüleyin"
