echo "Paketleri yükleme ve onlarla çalışma"
echo ""
echo "pkg install package - paketi yükler"
echo "pkg remove package - paketi kaldırır"
echo "pkg search package - paket depolarını arar"
echo "pkg list-installed - kurulu paketlerin bir listesini gösterecektir"
