echo "Network:"
echo ""
echo "ping host – Ana bilgisayara ping atın ve sonucu görüntüleyin"
echo "whois domain – bir alan adına ait whois bilgisini alma"
echo "dig domain – etki alanı DNS bilgilerini al"
echo "dig -x host – ana bilgisayarı geri dönüşümlü olarak ara"
echo "wget file – dosyayı indir"
echo "wget -c file – durdurulan indirmeye devam et"
