echo "Proses kontrolörleri:"
echo ""
echo "ps – mevcut aktif süreçlerinizi görüntüleyin"
echo "top – çalışan tüm işlemleri göster"
echo "kill pid – id pid ile süreci sonlandır"
echo "killall proc – proc adındaki tüm işlemleri sonlandır"
echo "bg – durdurulan ve arka plandaki görevlerin listesi; durdurulan görevin arka planda yürütülmesine devam etme"
echo "fg – son görevleri ön plana çıkarır"
echo "fg n – n görevini öne çıkar"
