echo "Search:"
echo ""
echo "grep pattern files – dosyalarda desen arama"
echo "grep -r pattern dir – dizindeki dir i yinelemeli olarak ara"
echo "command | grep pattern – komut çıktısında bir model arayın"
echo "locate file – dosya adındaki tüm dosyaları bul"
