echo "Sistem bilgisi"
echo "" 
echo "date – geçerli tarih ve saati görüntüleme"
echo "cal – geçerli ayın takvimini görüntüle"
echo "uptime – mevcut çalışma süresini göster"
echo "whoami – oturum açtığınız ad"
echo "uname -a – çekirdek hakkında bilgi göster"
echo "cat /proc/cpuinfo – CPU bilgisi"
echo "cat /proc/meminfo – hafıza bilgisi"
echo "man command – komutun kılavuzunu göster"
echo "df – disklerin kullanımı hakkında bilgi göster"
echo "du – geçerli dizinin "ağırlığını" göster"
echo "free – belleği kullanma ve değiştirme"
echo "whereis app – uygulamanın olası konumu"
echo "which app – varsayılan olarak hangi uygulama başlatılacak"
