
echo "dosya ve temel Komutlar:"
echo ""
echo "ls – dosya ve dizinlerin listesi"
echo "ls -al – gizli dizinler ve dosyalar içeren biçimlendirilmiş liste"
echo "cd dir – dizini şu şekilde değiştir: dir"
echo "cd – ana dizine geç"
echo "pwd – geçerli dizini göster"
echo "mkdir dir – katalog oluştur dir"
echo "rm -rf file – dosya veya klasörü sil"
echo "rm -r dir – dizini sil🫴🏻 dir"
echo "rm -r -f /path – dir dizinini sil"
echo "rm -f file – dosyayı zorla sil"
echo "rm -rf dir – dir dizinini zorla kaldır"
echo "cp file1 file2 – dosya1'i dosya2'ye kopyala"
echo "cp -r dir1 dir2 – dizin1'i dizin2'ye kopyalayın; yoksa dir2 dizini oluşturulacak"
echo "mv file1 file2 – dosya1'i dosya2'ye yeniden adlandırın veya taşıyın. dosya2 mevcut bir dizinse - dosya1'i dosya2 dizinine taşıyın"
echo "ln -s file link – dosya dosyasına sembolik bir bağlantı oluşturun"
echo "touch file – dosya oluştur"
echo "cat > file – dosyaya standart girdi gönder"
echo "more file – dosyanın içeriğini göster"
echo "head file – dosyanın ilk 10 satırını görüntüle"
echo "tail file – dosyanın son 10 satırını görüntüle"
echo "tail -f file – son 10 satırdan başlayarak dosyanın içeriğini büyüdükçe görüntüleyin"
echo ""
echo "Proses kontrolörleri:"
echo ""
echo "ps – mevcut aktif süreçlerinizi görüntüleyin"
echo "top – çalışan tüm işlemleri göster"
echo "kill pid – id pid ile süreci sonlandır"
echo "killall proc – proc adındaki tüm işlemleri sonlandır"
echo "bg – güncellenen ve arka plandaki görevlerin listesi;"
echo "fg – son görevleri ön plana çıkarır"
echo "fg n – n görevini öne çıkar"
echo ""
echo "Erişim hakları ve dosyalar"
echo ""
echo "chmod octal file – dosya haklarını kullanıcı, grup ve herkes için ayrı ayrı sekizli olarak ekleyerek değiştirin:"
echo "4 – okuma (r)"
echo "2 – kayıt (w)"
echo "1 – verim (x)"
echo "" 
echo "SSH:"
echo "" 
echo "ssh user@host – ana bilgisayara kullanıcı olarak bağlanacak"
echo "ssh -p port user@host – bağlantı noktası bağlantı noktasındaki ana bilgisayara kullanıcı olarak bağlanacak"
echo "ssh-copy-id user@host – kullanıcının etkinleştirmesi için anahtarınızı ana bilgisayara ekleyin şifre olmadan ve anahtarlarla giriş yapın"
echo ""
echo "Arama:"
echo ""
echo "grep pattern files – dosyalarda desen arama"
echo "grep -r pattern dir – içindeki deseni yinelemeli olarak ara🫴🏻 dir"
echo "command | grep pattern – komut çıktısında bir model arayın"
echo "locate file – dosya adındaki tüm dosyaları bul"
echo ""
echo "Sistem bilgisi"
echo "" 
echo "date – geçerli tarih ve saati görüntüleme"
echo "cal – geçerli ayın takvimini görüntüle"
echo "uptime – mevcut çalışma süresini göster"
echo "whoami – oturum açtığınız ad"
echo "uname -a – çekirdek hakkında bilgi göster"
echo "cat /proc/cpuinfo – CPU bilgisi"
echo "cat /proc/meminfo – hafıza bilgisi"
echo "man command – komut kılavuzunu göster"
echo "df – disklerin kullanımı hakkında bilgi ver"
echo "du – geçerli dizinin "ağırlığını" göster"
echo "free – belleği kullanma ve değiştirme"
echo "whereis app – uygulamanın olası konumu"
echo "which app – varsayılan olarak hangi uygulama başlatılacak"
echo ""
echo "Arşivler:"
echo "" 
echo "tar cf file.tar files – dosyaları içeren file.tar adında bir tar arşivi oluşturun"
echo "tar xf file.tar – file.tar paketini açın"
echo "tar czf file.tar.gz files – Gzip sıkıştırmasıyla tar arşivi oluşturma"
echo "tar xzf file.tar.gz – katranı Gzip ile açın"
echo "tar cjf file.tar.bz2 – Bzip2 sıkıştırmasıyla bir tar arşivi oluşturun"
echo "tar xjf file.tar.bz2 – katranı Bzip2 ile açın"
echo "gzip file – dosyayı sıkıştırın ve file.gz olarak yeniden adlandırın"
echo "gzip -d file.gz – file.gz dosyasını dosyaya çıkartın"
echo ""
echo "Network:"
echo ""
echo "ping host – Ana bilgisayara ping atın ve sonucu görüntüleyin"
echo "whois domain – bir alan adına ait whois bilgisini alma"
echo "dig domain – etki alanı DNS bilgilerini al"
echo "dig -x host – ana bilgisayarı geri dönüşümlü olarak ara"
echo "wget file – dosyayı indir"
echo "wget -c file – durdurulan indirmeye devam et"
echo ""
echo "Paketleri yükleme ve onlarla çalışma"
echo ""
echo "pkg install package - paketi yükler"
echo "pkg remove package - paketi kaldırır"
echo "pkg search package - paket depolarını arar"
echo "pkg list-installed - kurulu paketlerin bir listesini gösterecektir"
echo ""
echo "mucizelerin kalbinde kurulum:"
echo ""
echo "./configure"
echo "make"
echo "make install"
